# delegate_to_local.ps1 — Send a coding task to LM Studio's local server
# Usage: .\delegate_to_local.ps1 "Write an impl block for SpinLevel that..."
# Or:    Get-Content prompt.txt | .\delegate_to_local.ps1
#
# Requires: LM Studio running with server enabled (system tray → Start Server)
# Default endpoint: http://localhost:1234/v1/chat/completions
#
# All prompts and responses are logged to scripts/delegation_log.md
# Watch it live:  Get-Content scripts/delegation_log.md -Wait
# (open that in a separate terminal to see everything in real time)

param(
    [Parameter(ValueFromPipeline=$true)]
    [string]$PipedInput,

    [Parameter(Position=0)]
    [string]$Prompt,

    [string]$Url = "http://localhost:1234/v1/chat/completions",
    [int]$MaxTokens = 4096,
    [double]$Temperature = 0.2
)

# Resolve the prompt: argument wins, then pipeline, then bail
if ($Prompt) {
    $TaskPrompt = $Prompt
} elseif ($PipedInput) {
    $TaskPrompt = $PipedInput
} else {
    Write-Error "Usage: .\delegate_to_local.ps1 'prompt text'"
    Write-Error "   or: Get-Content prompt.txt | .\delegate_to_local.ps1"
    exit 1
}

# --- Logging setup ---
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$LogFile = Join-Path $ScriptDir "delegation_log.md"

# Create log file with header if it doesn't exist
if (-not (Test-Path $LogFile)) {
    @"
# Local LLM Delegation Log
> Auto-generated by delegate_to_local.ps1
> Watch live: ``Get-Content $LogFile -Wait``

---
"@ | Out-File -FilePath $LogFile -Encoding utf8
}

$Timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"

# Log the prompt
@"

## [$Timestamp] Delegation Request

**Prompt sent to local model:**

``````
$TaskPrompt
``````

"@ | Out-File -FilePath $LogFile -Append -Encoding utf8

# --- Build the request ---
$SystemPrompt = @"
You are a code generation assistant for the Charge Field Modeler project. The stack is Godot 4 + Rust (via gdext GDExtension) + Vulkan compute shaders (GLSL). Generate clean, well-commented code. Do not explain unless asked — just output the code. Use idiomatic Rust with proper error handling. For GDScript, use static typing. For GLSL, target Vulkan 1.1 / SPIR-V.
"@

$Body = @{
    messages = @(
        @{ role = "system"; content = $SystemPrompt }
        @{ role = "user"; content = $TaskPrompt }
    )
    max_tokens = $MaxTokens
    temperature = $Temperature
    stream = $false
} | ConvertTo-Json -Depth 4

# --- Call LM Studio ---
try {
    $Response = Invoke-RestMethod -Uri $Url -Method Post -Body $Body -ContentType "application/json" -ErrorAction Stop
} catch {
    $ErrorMsg = "Could not connect to LM Studio at $Url`nMake sure LM Studio is running and the server is started (system tray right-click → Start Server)"
    Write-Error $ErrorMsg

    # Log the failure
    @"
**ERROR:** $ErrorMsg

---
"@ | Out-File -FilePath $LogFile -Append -Encoding utf8
    exit 1
}

# --- Extract and return the response ---
if ($Response.choices -and $Response.choices.Count -gt 0) {
    $Output = $Response.choices[0].message.content

    # Log the response
    $Model = if ($Response.model) { $Response.model } else { "unknown" }
    $PromptTokens = if ($Response.usage.prompt_tokens) { $Response.usage.prompt_tokens } else { "?" }
    $CompletionTokens = if ($Response.usage.completion_tokens) { $Response.usage.completion_tokens } else { "?" }

    @"
**Response from local model** ($Model | prompt: $PromptTokens tokens | completion: $CompletionTokens tokens):

``````
$Output
``````

---
"@ | Out-File -FilePath $LogFile -Append -Encoding utf8

    # Output to stdout for Claude Code to capture
    Write-Output $Output

} elseif ($Response.error) {
    $ErrorMsg = "LM Studio error: $($Response.error)"
    Write-Error $ErrorMsg
    @"
**ERROR:** $ErrorMsg

---
"@ | Out-File -FilePath $LogFile -Append -Encoding utf8
    exit 1
} else {
    $ErrorMsg = "Unexpected response format from LM Studio"
    Write-Error $ErrorMsg
    @"
**ERROR:** $ErrorMsg
Raw response: $($Response | ConvertTo-Json -Depth 2)

---
"@ | Out-File -FilePath $LogFile -Append -Encoding utf8
    exit 1
}
